application: shortydev-app
version: 1
runtime: python
api_version: 1

handlers:

- url: /src/stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.py

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  

  